import CounterImage from "../../../assets/Images/Dashboard/Counter.svg";
import UserImage from "./../../../assets/Images/Dashboard/user.svg";
import MessagesImage from "../../../assets/Images/Dashboard/Messages.svg";
import AddImage from "../../../assets/Images/Dashboard/Add.svg";
import Elements from "../../../assets/Images/Dashboard/Elements.svg";
import Request from "../../../assets/Images/Dashboard/Request.svg";
import Rent from "../../../assets/Images/Dashboard/Rents.svg";
export const Dashboard_img = CounterImage;
export const UserInfo_img = UserImage;
export const Chat_img = MessagesImage;
export const AddProperty_img = AddImage;
export const Properties_img = Elements;
export const Requests_img = Request;
export const Accepted_img = Rent;
